services:
  - type: web
    name: tamil-auto
    env: node
    buildCommand: PUPPETEER_SKIP_DOWNLOAD=true npm install --omit=dev
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: IG_ACCESS_TOKEN
        sync: false
      - key: IG_BUSINESS_ACCOUNT_ID
        sync: false
      - key: IMGBB_API_KEY
        value: ""
      - key: IG_SESSION_ID
        sync: false
      - key: IG_CSRF_TOKEN
        sync: false
